version: 2.1

jobs:
  job_number1:
    environment: # These are only available inside this job only.
      CIRCLE_PIPELINE_ID: << pipeline.id >>
      WHICH_GIT_BRANCH: << pipeline.git.branch >>
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo $CIRCLE_PIPELINE_ID
      - run: echo $WHICH_GIT_BRANCH

workflows:
  workflow_number1:
    jobs:
      - job_number1